runtime: php
env: flex

runtime_config:
operating_system: "ubuntu22"
# document_root: .

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)